/* Generated by splitting the single-file port on 2026-08-26. */

import { Route, Routes } from "react-router-dom"

import { Nav } from "./components/Nav"
import { Footer } from "./components/Footer"
import { useSiteEffects } from "./effects"
import { Home } from "./pages/Home"
import { AgentPage } from "./pages/AgentPage"
import { PricingPage } from "./pages/PricingPage"
import { SecurityPage } from "./pages/SecurityPage"

export default function App() {
  useSiteEffects()

  return (
    <>
      <Nav />
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/agent" element={<AgentPage />} />
        <Route path="/pricing" element={<PricingPage />} />
        <Route path="/security" element={<SecurityPage />} />
        <Route path="*" element={<Home />} />
      </Routes>
      <Footer />
    </>
  )
}
