/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

import { useEffect } from "react"
import Lenis from "lenis"

/** Effects that belong to every page: easing, reveal, heading inflation,
 *  and the nav knowing which ground it currently sits on. */
export function useSiteEffects() {
  useEffect(() => {
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches
    const cleanups: Array<() => void> = []

    /* ---------- 1. reveal on scroll ---------- */
    const revealables = Array.from(document.querySelectorAll<HTMLElement>(".reveal"))
    if (reduce) {
      revealables.forEach((el) => el.classList.add("in"))
    } else {
      const ro = new IntersectionObserver(
        (entries) => {
          entries.forEach((e) => {
            if (e.isIntersecting) {
              e.target.classList.add("in")
              ro.unobserve(e.target)
            }
          })
        },
        { threshold: 0.12, rootMargin: "0px 0px -8% 0px" },
      )
      revealables.forEach((el, i) => {
        el.style.transitionDelay = Math.min(i % 6, 4) * 55 + "ms"
        ro.observe(el)
      })
      cleanups.push(() => ro.disconnect())
    }


    /* ---------- smooth scroll ---------- */
    /* Lenis eases the native scroll position rather than hijacking it with a
       transformed container: the scrollbar stays honest, arrow keys work, and
       screen readers still map to the document. Off entirely under
       prefers-reduced-motion — the easing is the thing being reduced. */
    if (!reduce) {
      const lenis = new Lenis({
        duration: 1.05,
        easing: (t: number) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
        smoothWheel: true,
        touchMultiplier: 1.6,
      })
      let raf = 0
      const tick = (time: number) => {
        lenis.raf(time)
        raf = requestAnimationFrame(tick)
      }
      raf = requestAnimationFrame(tick)

      /* In-page anchors go through Lenis so the jump is eased too. */
      const onAnchor = (e: MouseEvent) => {
        const link = (e.target as HTMLElement).closest<HTMLAnchorElement>('a[href^="#"]')
        if (!link) return
        const id = link.getAttribute("href")
        if (!id || id === "#") return
        const target = document.querySelector<HTMLElement>(id)
        if (!target) return
        e.preventDefault()
        lenis.scrollTo(target, { offset: -96 })
      }
      document.addEventListener("click", onAnchor)

      cleanups.push(() => {
        cancelAnimationFrame(raf)
        document.removeEventListener("click", onAnchor)
        lenis.destroy()
      })
    }


    /* ---------- nav over the dark first screen ---------- */
    /* The bar is fixed and the hero is dark, so the bar has to know which
       ground it is currently sitting on. Measured against the hero's own
       bottom edge rather than a hard scroll number, so it stays correct
       when the hero grows or the viewport changes. */
    const bar = document.querySelector<HTMLElement>("nav.bar")
    const hero = document.querySelector<HTMLElement>(".hero")
    if (bar && hero) {
      const syncBar = () => {
        const overDark = hero.getBoundingClientRect().bottom > 150
        bar.classList.toggle("on-dark", overDark)
      }
      syncBar()
      window.addEventListener("scroll", syncBar, { passive: true })
      window.addEventListener("resize", syncBar)
      cleanups.push(() => {
        window.removeEventListener("scroll", syncBar)
        window.removeEventListener("resize", syncBar)
      })
    }


    /* ---------- section headings inflate as they arrive ---------- */
    /* Dia grows elements when they enter the frame rather than on hover:
       the page feels alive while scrolling and stays still while reading. */
    const inflatables = Array.from(document.querySelectorAll<HTMLElement>(".inflate"))
    if (reduce) {
      inflatables.forEach((el) => el.classList.add("in"))
    } else {
      const io = new IntersectionObserver(
        (entries) => {
          entries.forEach((e) => {
            if (e.isIntersecting) {
              e.target.classList.add("in")
              io.unobserve(e.target)
            }
          })
        },
        { threshold: 0.25, rootMargin: "0px 0px -12% 0px" },
      )
      inflatables.forEach((el) => io.observe(el))
      cleanups.push(() => io.disconnect())
    }


    return () => cleanups.forEach((fn) => fn())
  }, [])
}

/** Effects that only exist where their markup does. Each bails out quietly
 *  when its elements are absent, so a page can mount any subset. */
export function useHomeEffects() {
  useEffect(() => {
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches
    const cleanups: Array<() => void> = []

    /* ---------- 2. the schedule ---------- */
    const DAY_START = 9
    const HOURS = 8.5
    const PX_HOUR = 64

    const top = (t: number) => (t - DAY_START) * PX_HOUR
    const height = (a: number, b: number) => Math.max((b - a) * PX_HOUR - 4, 26)
    const clock = (t: number) => {
      const h = Math.floor(t)
      const m = Math.round((t - h) * 60)
      return (h < 10 ? "0" : "") + h + ":" + (m < 10 ? "0" : "") + m
    }

    type Item = { id: string; title: string; kind: string; start: [number, number]; end: [number, number] }
    const PLAN: Item[] = [
      { id: "standup", title: "Standup", kind: "fixed", start: [9, 9.5], end: [9, 9.5] },
      { id: "copy", title: "Landing copy", kind: "auto", start: [10, 11.5], end: [10, 11.5] },
      { id: "invoices", title: "Invoices", kind: "auto", start: [15.5, 16], end: [11.5, 12] },
      { id: "lunch", title: "Lunch", kind: "fixed", start: [12, 13], end: [12, 13] },
      { id: "pricing", title: "Ship pricing page", kind: "auto", start: [14, 15.5], end: [15, 16.5] },
      { id: "kim", title: "1:1 with Kim", kind: "fixed", start: [16.5, 17], end: [16.5, 17] },
    ]
    const ARRIVAL = { id: "review", title: "Design review", kind: "fixed", at: [14, 15] as [number, number] }

    const track = document.getElementById("track")
    const hoursEl = document.getElementById("hours")
    const capText = document.getElementById("captiontext")
    const caption = document.getElementById("caption")
    const nowLine = document.getElementById("nowline")

    if (track && hoursEl && capText && caption && nowLine) {
      let nodes: Record<string, HTMLElement> = {}
      let timers: number[] = []

      for (let h = DAY_START; h <= DAY_START + Math.floor(HOURS) - 1; h++) {
        const row = document.createElement("div")
        row.className = "hour"
        row.textContent = clock(h)
        hoursEl.appendChild(row)
      }
      nowLine.style.top = top(13.6) + "px"

      const place = (el: HTMLElement, a: number, b: number) => {
        el.style.top = top(a) + "px"
        el.style.height = height(a, b) + "px"
        el.classList.toggle("short", b - a <= 0.5)
        const meta = el.querySelector<HTMLElement>(".m")
        if (meta) meta.textContent = clock(a) + " – " + clock(b)
      }

      const make = (item: { title: string; kind: string }, at: [number, number]) => {
        const el = document.createElement("div")
        el.className = "ev"
        el.setAttribute("data-kind", item.kind)
        el.innerHTML = '<div class="t"></div><div class="m"></div>'
        el.querySelector<HTMLElement>(".t")!.textContent = item.title
        place(el, at[0], at[1])
        track.appendChild(el)
        return el
      }

      const build = () => {
        timers.forEach(clearTimeout)
        timers = []
        track.querySelectorAll(".ev").forEach((n) => n.remove())
        nodes = {}
        PLAN.forEach((item) => {
          nodes[item.id] = make(item, item.start)
        })
        caption.classList.remove("live")
        capText.textContent = "Your day as you left it."
      }

      const after = (ms: number, fn: () => void) => {
        timers.push(window.setTimeout(fn, ms))
      }

      const run = () => {
        build()
        if (reduce) {
          PLAN.forEach((i) => place(nodes[i.id], i.end[0], i.end[1]))
          make(ARRIVAL, ARRIVAL.at)
          capText.textContent = "Design review landed at 14:00. Two blocks moved. Nothing was dropped."
          return
        }

        after(1500, () => {
          caption.classList.add("live")
          capText.textContent = "Design review invite accepted — 14:00 to 15:00."
          const el = make(ARRIVAL, ARRIVAL.at)
          el.classList.add("entering")
          nodes[ARRIVAL.id] = el
          requestAnimationFrame(() => {
            requestAnimationFrame(() => el.classList.remove("entering"))
          })
        })

        after(2900, () => {
          capText.textContent = "It lands on Ship pricing page. Rebuilding the rest of the day."
          nodes.pricing.classList.add("moved")
        })

        after(3700, () => {
          PLAN.forEach((item) => {
            if (item.start[0] !== item.end[0]) {
              place(nodes[item.id], item.end[0], item.end[1])
              nodes[item.id].classList.add("moved")
            }
          })
        })

        after(4800, () => {
          capText.textContent = "Ship pricing page → 15:00. Invoices → 11:30. Still done before your 1:1."
        })

        after(7200, () => {
          caption.classList.remove("live")
          capText.textContent = "Two blocks moved. Nothing was dropped, and nothing needed you."
          Object.keys(nodes).forEach((k) => nodes[k].classList.remove("moved"))
        })
      }

      let started = false
      const so = new IntersectionObserver(
        (entries) => {
          entries.forEach((e) => {
            if (e.isIntersecting && !started) {
              started = true
              run()
              so.disconnect()
            }
          })
        },
        { threshold: 0.35 },
      )
      so.observe(track)
      cleanups.push(() => so.disconnect())

      const replayBtn = document.getElementById("replay")
      const seeBtn = document.getElementById("see")
      const onReplay = () => run()
      const onSee = () => {
        document.querySelector(".stage")?.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "center" })
        run()
      }
      replayBtn?.addEventListener("click", onReplay)
      seeBtn?.addEventListener("click", onSee)
      cleanups.push(() => {
        replayBtn?.removeEventListener("click", onReplay)
        seeBtn?.removeEventListener("click", onSee)
        timers.forEach(clearTimeout)
      })
    }


    /* ---------- 3. steps 01 02 03 ---------- */
    const steps = Array.from(document.querySelectorAll<HTMLElement>(".step"))
    const panels = Array.from(document.querySelectorAll<HTMLElement>(".panel"))

    const lightStep = (n: string | null) => {
      steps.forEach((s) => s.classList.toggle("on", s.getAttribute("data-step") === String(n)))
      panels.forEach((p) => p.classList.toggle("on", p.getAttribute("data-panel") === String(n)))
    }

    const stepHandlers: Array<[HTMLElement, () => void]> = []
    steps.forEach((s) => {
      const handler = () => lightStep(s.getAttribute("data-step"))
      s.addEventListener("click", handler)
      stepHandlers.push([s, handler])
    })
    cleanups.push(() => stepHandlers.forEach(([s, h]) => s.removeEventListener("click", h)))

    if (!reduce) {
      const po = new IntersectionObserver(
        (entries) => {
          entries.forEach((e) => {
            if (e.isIntersecting) lightStep(e.target.getAttribute("data-step"))
          })
        },
        { threshold: 0.6, rootMargin: "-20% 0px -30% 0px" },
      )
      steps.forEach((s) => po.observe(s))
      cleanups.push(() => po.disconnect())
    }


    /* ---------- 4. sticky mobile CTA ---------- */
    const sticky = document.getElementById("stickycta")
    const heroCta = document.querySelector(".hero-cta")
    if (sticky && heroCta) {
      const io = new IntersectionObserver(
        (entries) => {
          entries.forEach((e) => sticky.classList.toggle("on", !e.isIntersecting))
        },
        { threshold: 0 },
      )
      io.observe(heroCta)
      cleanups.push(() => io.disconnect())
    }


    /* ---------- 5. FAQ — one open at a time ---------- */
    const qas = Array.from(document.querySelectorAll<HTMLDetailsElement>(".qa"))
    const qaHandlers: Array<[HTMLDetailsElement, () => void]> = []
    qas.forEach((d) => {
      const handler = () => {
        if (!d.open) return
        qas.forEach((o) => {
          if (o !== d) o.open = false
        })
      }
      d.addEventListener("toggle", handler)
      qaHandlers.push([d, handler])
    })
    cleanups.push(() => qaHandlers.forEach(([d, h]) => d.removeEventListener("toggle", h)))


    return () => cleanups.forEach((fn) => fn())
  }, [])
}
