/* Generated by splitting the single-file port on 2026-08-26. */

import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { BrowserRouter } from "react-router-dom"

import App from "./App"
import "./index.css"

/* View Transitions: the browser animates the swap between routes itself.
   Motion gets this free from Astro; react-router exposes the same platform
   API behind a flag. Firefox has no support yet and simply jumps, which is
   the correct fallback. */
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
)
