export const COMMON_TIME_ZONES = [
  "UTC",
  "America/Anchorage",
  "America/Chicago",
  "America/Denver",
  "America/Edmonton",
  "America/Halifax",
  "America/Los_Angeles",
  "America/Mexico_City",
  "America/Montreal",
  "America/New_York",
  "America/Phoenix",
  "America/Toronto",
  "America/Vancouver",
  "America/Winnipeg",
  "America/Bogota",
  "America/Buenos_Aires",
  "America/Caracas",
  "America/Lima",
  "America/Santiago",
  "America/Sao_Paulo",
  "Europe/Amsterdam",
  "Europe/Athens",
  "Europe/Berlin",
  "Europe/Brussels",
  "Europe/Budapest",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Helsinki",
  "Europe/Istanbul",
  "Europe/Lisbon",
  "Europe/London",
  "Europe/Madrid",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Prague",
  "Europe/Rome",
  "Europe/Stockholm",
  "Europe/Vienna",
  "Europe/Warsaw",
  "Europe/Zurich",
  "Asia/Bangkok",
  "Asia/Dubai",
  "Asia/Hong_Kong",
  "Asia/Jakarta",
  "Asia/Jerusalem",
  "Asia/Karachi",
  "Asia/Kolkata",
  "Asia/Kuala_Lumpur",
  "Asia/Manila",
  "Asia/Riyadh",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Taipei",
  "Asia/Tokyo",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Johannesburg",
  "Africa/Lagos",
  "Africa/Nairobi",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Darwin",
  "Australia/Melbourne",
  "Australia/Perth",
  "Australia/Sydney",
  "Pacific/Auckland",
  "Pacific/Fiji",
  "Pacific/Honolulu",
] as const;

const TIME_ZONE_ABBREVIATIONS: Record<string, string> = {
  "Central European Standard Time": "CET",
  "Central European Summer Time": "CEST",
  "Western European Standard Time": "WET",
  "Western European Summer Time": "WEST",
  "Eastern European Standard Time": "EET",
  "Eastern European Summer Time": "EEST",
  "Greenwich Mean Time": "GMT",
  "British Summer Time": "BST",
  "Coordinated Universal Time": "UTC",
  "Eastern Standard Time": "EST",
  "Eastern Daylight Time": "EDT",
  "Central Standard Time": "CST",
  "Central Daylight Time": "CDT",
  "Mountain Standard Time": "MST",
  "Mountain Daylight Time": "MDT",
  "Pacific Standard Time": "PST",
  "Pacific Daylight Time": "PDT",
};

export function getTimeZoneLabel(timeZone: string, date = new Date()) {
  const name = (token: "long" | "short") =>
    new Intl.DateTimeFormat("en-US", {
      timeZone,
      timeZoneName: token,
    })
      .formatToParts(date)
      .find((part) => part.type === "timeZoneName")?.value ?? timeZone;

  return TIME_ZONE_ABBREVIATIONS[name("long")] ?? name("short");
}

export function getTimeZoneDisplayName(timeZone: string) {
  return timeZone.replace(/_/g, " ");
}
