import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      ".codex/**",
      ".agents/**",
      // Separate Git worktrees are validated from their own roots. Traversing
      // them here lints other branches as if they belonged to this checkout.
      ".claude/**",
      "dist/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "public/sw.js",
      // Self-contained sub-projects: each carries its own tsconfig, its own
      // dependency set and its own build (Vite, not Next). Linting them from
      // the root resolves their imports against the root's node_modules, which
      // they do not share, so every import reads as missing. They are gated by
      // their own tooling instead.
      "landing/**",
      "landing from figma/**",
      "New ui /**",
      // Design references, not application code: HTML prototypes and the
      // exported design-system kit, including its pre-minified bundle. Linting
      // a bundle reports on its minifier, not on anything anyone can fix here.
      "design-refs/**",
      "Needt Design System/**",
      // The downloaded Claude Design bundle and the folder it replaces. These
      // are prototypes written as classic script tags: every component is a
      // window global and nothing is a module, so import resolution, no-undef
      // and the react plugin all report on the format rather than on a defect.
      // `npm run tokens:sync` vendors the parts the app uses.
      "Content height and label fixes/**",
      "needt-app-design/**",
      // Retired in place rather than deleted, so the history stays recoverable
      // while the port runs. Nothing here is built or shipped.
      "_archive-figma-make/**",
      "_superseded/**",
      // Untracked sync scratch area, not part of the application build.
      "pf-sync/**",
      // Generated by `next build` and gitignored. Next 15.5 adds a
      // `routes.d.ts` triple-slash reference that trips
      // @typescript-eslint/triple-slash-reference, and the file must not be
      // edited by hand.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    files: ["**/*.js", "**/*.cjs"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
];

export default eslintConfig;
