/* Generated by splitting the single-file port on 2026-08-26. */

export function Footer() {
  return (
    <footer>
      <div className="wrap">
        <div className="fcta">
          <p className="display reveal">Ready for a better day?</p>
          <a className="btn btn-solid btn-lg reveal" href="https://use.needt.app">
            Start my free plan
          </a>
          <p className="fine reveal">
            Free while it is in beta. Works on any browser, and with the calendar you already have.
          </p>
        </div>

        <div className="fcols reveal">
          <div className="fcol">
            <h5>Product</h5>
            <a href="#how">How it works</a>
            <a href="#agent">The agent</a>
            <a href="#inside">Inside</a>
            <a href="#pricing">Pricing</a>
          </div>
          <div className="fcol">
            <h5>Connect</h5>
            <span>Google Calendar</span>
            <span>Outlook</span>
            <span>CalDAV</span>
            <span>MCP · soon</span>
          </div>
          <div className="fcol">
            <h5>Company</h5>
            <a href="#who">Who is behind it</a>
            <a href="#faq">FAQ</a>
            <a href="mailto:hello@needt.app">Contact</a>
          </div>
          <div className="fcol">
            <h5>Legal</h5>
            <a href="https://use.needt.app/privacy">Privacy</a>
            <a href="https://use.needt.app/terms">Terms</a>
            <a href="https://use.needt.app">Sign in</a>
          </div>
        </div>

        <div className="fbot">
          <span>Copyright © 2026</span>
          <span className="built">
            Designed and built by one person
            <br />
            in Switzerland
          </span>
          <span>Needt</span>
        </div>
      </div>
      <div className="bloom" aria-hidden="true"></div>
    </footer>
  )
}
