/* Generated by splitting the single-file port on 2026-08-26. */

import { useEffect, useRef, useState } from "react"
import { Link, useLocation } from "react-router-dom"

/** The product menu. Motion and Notion both open a panel with grouped
 *  columns rather than a plain dropdown, because a plain dropdown cannot
 *  hold a description — and the description is what makes the difference
 *  between a list of nouns and something a stranger can read. */
const PRODUCT = [
  {
    group: "The day",
    items: [
      { to: "/#how", title: "Schedule", note: "One canvas for the day, rebuilt when something lands" },
      { to: "/#inside", title: "Tasks", note: "Sized, placed, and moved when the day changes" },
      { to: "/agent", title: "The agent", note: "Reads the day, proposes the change, waits for you" },
    ],
  },
  {
    group: "Around it",
    items: [
      { to: "/#inside", title: "Pages", note: "Notes that live beside the work, not in a second app" },
      { to: "/#inside", title: "Focus", note: "A session against a block that already exists" },
      { to: "/#connections", title: "Integrations", note: "Google, Outlook, CalDAV, and your inbox" },
    ],
  },
]

export function Nav() {
  const [open, setOpen] = useState(false)
  const wrapRef = useRef<HTMLDivElement>(null)
  const closeTimer = useRef<number | undefined>(undefined)
  const { pathname } = useLocation()

  /* Route change closes the panel — otherwise it survives the transition
     and hangs over the new page. */
  useEffect(() => setOpen(false), [pathname])

  useEffect(() => {
    if (!open) return
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false)
    const onClick = (e: MouseEvent) => {
      if (!wrapRef.current?.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener("keydown", onKey)
    document.addEventListener("mousedown", onClick)
    return () => {
      document.removeEventListener("keydown", onKey)
      document.removeEventListener("mousedown", onClick)
    }
  }, [open])

  /* Pointer intent, not raw hover: a small delay on leaving stops the panel
     flickering when the cursor crosses the gap between trigger and panel. */
  const hold = () => window.clearTimeout(closeTimer.current)
  const release = () => {
    closeTimer.current = window.setTimeout(() => setOpen(false), 140)
  }

  return (
    <header>
      <div className="wrap" style={{ padding: "0 16px" }}>
        <nav className="bar" ref={wrapRef as never} onMouseLeave={release} onMouseEnter={hold}>
          <Link className="mark" to="/" viewTransition>
            <span></span>Needt
          </Link>

          <div className="navlinks">
            <button
              type="button"
              className={"navtrigger" + (open ? " open" : "")}
              aria-expanded={open}
              aria-haspopup="true"
              onClick={() => setOpen((v) => !v)}
              onMouseEnter={() => {
                hold()
                setOpen(true)
              }}
            >
              Product
              <svg viewBox="0 0 12 12" width="11" height="11" aria-hidden="true">
                <path d="M2.5 4.5 6 8l3.5-3.5" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
            <Link to="/pricing" viewTransition>Pricing</Link>
            <Link to="/security" viewTransition>Security</Link>
          </div>

          <a className="btn btn-solid" href="https://use.needt.app">
            Start free
          </a>

          <div className={"megamenu" + (open ? " open" : "")} role="menu" aria-hidden={!open}>
            <div className="megagrid">
              {PRODUCT.map((col) => (
                <div className="megacol" key={col.group}>
                  <p className="megaeyebrow">{col.group}</p>
                  {col.items.map((it) => (
                    <Link className="megaitem" to={it.to} key={it.title} role="menuitem" viewTransition>
                      <span className="megaicon" aria-hidden="true" />
                      <span>
                        <strong>{it.title}</strong>
                        <em>{it.note}</em>
                      </span>
                    </Link>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </nav>
      </div>
    </header>
  )
}
