/* Generated by splitting the single-file port on 2026-08-26. */

export function StickyCta() {
  return (
    <div className="sticky-cta" id="stickycta">
      <a href="https://use.needt.app">
        Start my free plan <span>no card</span>
      </a>
    </div>
  )
}
