/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Agent() {
  return (
    <>
    {/* ============ THE AGENT ============ */}
    <section className="agent" id="agent">
      <div className="wrap">
        <div className="agent-head">
          <p className="eyebrow reveal" style={{ marginBottom: "16px" }}>
            The agent
          </p>
          <h2 className="reveal inflate">Not a chat box bolted onto a calendar.</h2>
          <p className="lede reveal" style={{ marginTop: "18px", maxWidth: "52ch" }}>
            Twenty-two tools that act on your real schedule, your real pages and your real inbox — and one that
            remembers when you correct it.
          </p>
        </div>

        <div className="agent-grid">
          <div className="cap reveal">
            <div className="ic">
              <svg viewBox="0 0 24 24">
                <path d="M4 7h16M4 12h11M4 17h7" />
              </svg>
            </div>
            <h4>Turns a paragraph into a week</h4>
            <p>
              Dump everything you are carrying in one message. It comes back as separate tasks, sized, and placed in
              slots that exist.
            </p>
            <div className="tools">
              <span className="tool">parse_brain_dump</span>
              <span className="tool">create_task</span>
              <span className="tool">auto_schedule</span>
              <span className="tool">query_schedule</span>
            </div>
          </div>

          <div className="cap reveal">
            <div className="ic">
              <svg viewBox="0 0 24 24">
                <path d="M3 6h13M3 12h18M3 18h9" />
                <path d="M18 4l3 3-3 3" />
              </svg>
            </div>
            <h4>Moves things, and asks first</h4>
            <p>
              Edits, reschedules and deletions that change your day require confirmation. The proposal is shown
              before anything is applied.
            </p>
            <div className="tools">
              <span className="tool">edit_task</span>
              <span className="tool">delete_task</span>
              <span className="tool">manage_projects</span>
            </div>
          </div>

          <div className="cap reveal">
            <div className="ic">
              <svg viewBox="0 0 24 24">
                <rect x="3" y="5" width="18" height="14" rx="2" />
                <path d="M3 8l9 6 9-6" />
              </svg>
            </div>
            <h4>Reads your inbox, never sends</h4>
            <p>
              Search locally synced mail, open one message, turn it into a scheduled task. It has no ability to send
              anything on your behalf.
            </p>
            <div className="tools">
              <span className="tool">search_mail</span>
              <span className="tool">get_message</span>
              <span className="tool">create_task_from_email</span>
            </div>
          </div>

          <div className="cap wide reveal">
            <div className="ic">
              <svg viewBox="0 0 24 24">
                <path d="M12 3a4 4 0 00-4 4v1a3 3 0 000 6v2a3 3 0 003 3h1" />
                <path d="M12 3a4 4 0 014 4v1a3 3 0 010 6v2a3 3 0 01-3 3h-1" />
              </svg>
            </div>
            <h4>It remembers what you correct</h4>
            <p>
              Correct it once and it keeps the correction. Never schedule deep work before ten. Always leave thirty
              minutes after a call. The kind of thing you should not have to repeat, and here you do not.
            </p>
            <p className="quote">
              “Don&apos;t put anything before 10am on Mondays.”
              <span>remembered · applied to every reschedule since</span>
            </p>
            <div className="tools" style={{ marginTop: "16px" }}>
              <span className="tool">remember</span>
              <span className="tool">forget</span>
              <span className="tool">list_memories</span>
            </div>
          </div>

          <div className="cap reveal">
            <div className="ic">
              <svg viewBox="0 0 24 24">
                <circle cx="12" cy="12" r="8" />
                <path d="M12 8v4l3 2" />
              </svg>
            </div>
            <h4>Runs focus, reports honestly</h4>
            <p>
              Start a session against a block that already exists, stop it, and read the week back — time actually
              spent, not time intended.
            </p>
            <div className="tools">
              <span className="tool">start_focus_session</span>
              <span className="tool">stop_focus_session</span>
              <span className="tool">get_focus_stats</span>
            </div>
          </div>

          <div className="cap reveal">
            <div className="ic">
              <svg viewBox="0 0 24 24">
                <path d="M5 4h11l3 3v13H5z" />
                <path d="M8 11h8M8 15h5" />
              </svg>
            </div>
            <h4>Writes into your pages</h4>
            <p>
              Finds the right document, proposes the edit, and waits. Your notes are never rewritten without you
              seeing the change first.
            </p>
            <div className="tools">
              <span className="tool">list_pages</span>
              <span className="tool">search_pages</span>
              <span className="tool">propose_page_changes</span>
            </div>
          </div>
        </div>

        <div className="models reveal">
          <span className="lbl">Bring your own model</span>
          <div className="chipset">
            <span className="chip">Needt hosted</span>
            <span className="chip">Anthropic</span>
            <span className="chip">OpenAI</span>
            <span className="chip">Grok</span>
            <span className="chip">GLM</span>
            <span className="chip">Custom endpoint</span>
            <span className="chip soon">MCP server</span>
          </div>
        </div>
      </div>
    </section>
    </>
  )
}
