/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Faq() {
  return (
    <>
    {/* ============ FAQ ============ */}
    <section className="faq" id="faq">
      <div className="wrap">
        <h2 className="reveal inflate">Reasonable questions.</h2>

        <details className="qa reveal">
          <summary>Does it move things without asking?</summary>
          <p>
            No. Every reschedule is shown as a proposal first — what moved, where it went, what stayed put. You keep
            it or you undo it. The same rule applies to the agent: anything that edits, deletes or changes your
            working hours requires confirmation.
          </p>
        </details>

        <details className="qa reveal">
          <summary>Can the agent send email as me?</summary>
          <p>
            It cannot. Mail access is read-only by design — it can search your locally synced messages, open one,
            and turn it into a task. There is no tool in the catalogue that sends anything.
          </p>
        </details>

        <details className="qa reveal">
          <summary>Do I have to use your AI?</summary>
          <p>
            No. Needt works as a planner with the agent switched off. If you do want it, you can use the hosted
            model or point Needt at your own Anthropic, OpenAI, Grok, GLM or custom endpoint — your key, your bill,
            your data going where you chose.
          </p>
        </details>

        <details className="qa reveal">
          <summary>What happens to my calendar?</summary>
          <p>
            Needt syncs it into its own database and works on that copy, so the app stays fast and keeps working
            when a provider is slow. Events you did not create in Needt are never rewritten — they are the fixed
            points the rest of the day is arranged around.
          </p>
        </details>

        <details className="qa reveal">
          <summary>Why is there no free trial on Free?</summary>
          <p>
            Because Free is not a trial. One calendar, fifteen auto-scheduled tasks a month, a board and the focus
            timer, with no expiry. Pro is for when the limits start to hurt, and it has a fourteen-day trial without
            a card.
          </p>
        </details>

        <details className="qa reveal">
          <summary>Is my data used to train anything?</summary>
          <p>
            No. Your schedule, pages and mail are yours. When you bring your own model key, requests go straight to
            that provider under your account and their terms.
          </p>
        </details>
      </div>
    </section>
    </>
  )
}
