/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Founder() {
  return (
    <>
    {/* ============ WHO IS BEHIND IT ============ */}
    <section className="founder" id="who">
      <div className="wrap">
        <p className="eyebrow reveal" style={{ marginBottom: "24px" }}>
          Who is behind it
        </p>
        <div className="founder-card reveal">
          <div className="avatar">M</div>
          <div>
            <p>
              Needt is built by <strong>one person</strong>. I made it because every planner I tried asked me to
              maintain it — to re-sort the list when a meeting landed, to decide again what fits before lunch. That
              is the work I wanted the tool to do.
            </p>
            <p>
              It is early. Some of it is rough, the roadmap is public, and if you write to me you get me, not a
              ticket queue. That is the trade: you are not buying a finished thing from a company, you are getting an
              unfinished one from someone who uses it every day and answers.
            </p>
            <div className="sig">
              <span>Maksym · Switzerland</span>
              <a href="mailto:hello@needt.app">hello@needt.app</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    </>
  )
}
