/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Hero() {
  return (
    <>
    {/* ============ HERO ============ */}
    <section className="hero">
      <div className="wrap">
        <p className="eyebrow reveal">A planner that reschedules itself</p>
        <h1 className="display reveal">Something always moves.</h1>
        <p className="lede reveal">
          A meeting lands. A task runs long. Needt rebuilds the rest of the day around it — and shows you the day it
          made before you keep it.
        </p>
        <div className="hero-cta reveal">
          <a className="btn btn-solid btn-lg" href="https://use.needt.app">
            Start my free plan
          </a>
          <button className="btn btn-ghost btn-lg" id="see">
            See it move
          </button>
        </div>
        <p className="hero-note reveal">Free while it is in beta. No card.</p>

        <div className="stage reveal">
          <div className="window">
            <div className="chrome">
              <span className="dot r"></span>
              <span className="dot y"></span>
              <span className="dot g"></span>
              <span className="label">Tuesday</span>
              <button className="replay" id="replay">
                Replay
              </button>
            </div>
            <div className="day">
              <div className="hours" id="hours"></div>
              <div className="track" id="track">
                <div className="now" id="nowline"></div>
              </div>
            </div>
            <div className="caption" id="caption">
              <span className="pulse"></span>
              <span id="captiontext">Your day as you left it.</span>
            </div>
          </div>
        </div>
      </div>
    </section>
    </>
  )
}
