/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Inside() {
  return (
    <>
    {/* ============ INSIDE ============ */}
    <section className="feat" id="inside">
      <div className="wrap">
        <div className="feat-head">
          <p className="eyebrow reveal" style={{ marginBottom: "16px" }}>
            Inside
          </p>
          <h2 className="reveal inflate">The rest of the week lives here too.</h2>
        </div>
        <div className="cards">
          <div className="card reveal">
            <span className="tag">Boards</span>
            <p>
              Custom columns, drag and drop, saved views — and documents in the same workspace. A task on a board is
              the same task on your calendar, not a copy of it.
            </p>
            <div className="mock">
              <div className="mk">
                <div className="mk-bar">
                  <i></i>
                  <i></i>
                  <i></i>
                  <b>Launch</b>
                </div>
                <div className="mk-board">
                  <div className="mk-col">
                    <span>To do</span>
                    <div className="mk-t">Pricing copy</div>
                    <div className="mk-t">Outreach list</div>
                    <div className="mk-t">Legal review</div>
                    <div className="mk-t">Creem products</div>
                  </div>
                  <div className="mk-col">
                    <span>Doing</span>
                    <div className="mk-t b">Ship pricing page</div>
                    <div className="mk-t a">Landing copy</div>
                    <div className="mk-t">Agent memory</div>
                  </div>
                  <div className="mk-col">
                    <span>Done</span>
                    <div className="mk-t">Domain + DNS</div>
                    <div className="mk-t">Calendar sync</div>
                    <div className="mk-t">Outlook app</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="card reveal">
            <span className="tag">Focus</span>
            <p>
              Not a separate screen. The block you chose grows, the rest of the day dims, and the timer runs against
              the slot that was already there.
            </p>
            <div className="mock">
              <div className="mk">
                <div className="mk-bar">
                  <i></i>
                  <i></i>
                  <i></i>
                  <b>Focus · 68%</b>
                </div>
                <div className="mk-focus">
                  <div className="ring">
                    <b>41:12</b>
                  </div>
                  <div className="mk-dim">
                    <div className="f"></div>
                    <div className="live"></div>
                    <div className="f"></div>
                    <div className="f"></div>
                  </div>
                  <div className="mk-dim" style={{ flexBasis: "100%" }}>
                    <div className="f"></div>
                    <div className="f"></div>
                    <div className="f"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="card reveal">
            <span className="tag">Moodboards</span>
            <p>
              References, sketches and screenshots on a full Excalidraw canvas that belongs to the project it came
              from — not to a tab you lose by Thursday.
            </p>
            <div className="mock">
              <div className="mk">
                <div className="mk-bar">
                  <i></i>
                  <i></i>
                  <i></i>
                  <b>Identity</b>
                </div>
                <div className="mk-canvas">
                  <i></i>
                  <i></i>
                  <i></i>
                  <i></i>
                  <i></i>
                  <i></i>
                  <i></i>
                </div>
              </div>
            </div>
          </div>

          <div className="card reveal">
            <span className="tag">Command palette</span>
            <p>
              Create, schedule, jump, search, reschedule. Every action has a keystroke, because a planner you have
              to click through is a planner you stop opening.
            </p>
            <div className="mock">
              <div className="mk">
                <div className="mk-bar">
                  <i></i>
                  <i></i>
                  <i></i>
                  <b>⌘K</b>
                </div>
                <div className="mk-pal">
                  <div className="mk-inp">
                    Schedule<kbd>⌘K</kbd>
                  </div>
                  <div className="mk-row on">
                    <s></s>Auto-schedule this week<em>enter</em>
                  </div>
                  <div className="mk-row">
                    <s></s>Move Ship pricing page<em>⌘M</em>
                  </div>
                  <div className="mk-row">
                    <s></s>Start focus<em>⌘F</em>
                  </div>
                  <div className="mk-row">
                    <s></s>New task from email<em>⌘E</em>
                  </div>
                  <div className="mk-row">
                    <s></s>Jump to Today<em>⌘1</em>
                  </div>
                  <div className="mk-row">
                    <s></s>Open moodboard<em>⌘B</em>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    </>
  )
}
