/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Pricing() {
  return (
    <>
    {/* ============ PRICING ============ */}
    <section className="pricing" id="pricing">
      <div className="wrap">
        <div className="price-head">
          <div>
            <p className="eyebrow reveal" style={{ marginBottom: "16px" }}>
              Pricing
            </p>
            <h2 className="reveal inflate">Cheaper than the hour it saves.</h2>
          </div>
          <p className="price-note reveal">
            One boundary, not three. Free is a real product you can stay on. Pro removes the limits.
          </p>
        </div>

        <div className="tablewrap reveal">
          <table className="cmp">
            <colgroup>
              <col className="c-feat" />
              <col className="c-free" />
              <col className="c-pro" />
            </colgroup>
            <thead>
              <tr>
                <th></th>
                <th className="plan-h">
                  <span className="nm">Free</span>
                  <span className="amt">$0</span>
                  <span className="per">forever</span>
                </th>
                <th className="plan-h pro">
                  <span className="nm">Pro</span>
                  <span className="amt">$6</span>
                  <span className="per">per month · $60 a year</span>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="feat-name">
                  Calendars connected<small>Google, Outlook, CalDAV</small>
                </td>
                <td className="val">One</td>
                <td className="val yes pro">Unlimited</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Auto-scheduled tasks<small>Placed around your real week</small>
                </td>
                <td className="val">15 a month</td>
                <td className="val yes pro">Unlimited</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Reschedule preview<small>See the day before you keep it</small>
                </td>
                <td className="val yes">Included</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Boards<small>Columns, drag and drop, saved views</small>
                </td>
                <td className="val">One</td>
                <td className="val yes pro">Unlimited</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Pages<small>Documents in the same workspace</small>
                </td>
                <td className="val">Three</td>
                <td className="val yes pro">Unlimited</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Real-time collaboration<small>Two people in one document</small>
                </td>
                <td className="val no">—</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Moodboards<small>Infinite Excalidraw canvas</small>
                </td>
                <td className="val no">—</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Focus timer<small>Sessions against real blocks</small>
                </td>
                <td className="val yes">Included</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Focus stats<small>Time spent, week by week</small>
                </td>
                <td className="val no">—</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  The agent<small>22 tools on your real data</small>
                </td>
                <td className="val">Limited</td>
                <td className="val yes pro">Full</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Agent memory<small>It keeps your corrections</small>
                </td>
                <td className="val no">—</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Bring your own model<small>Anthropic, OpenAI, Grok, GLM, custom</small>
                </td>
                <td className="val no">—</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Inbox → task<small>Read-only mail, never sends</small>
                </td>
                <td className="val no">—</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  Command palette<small>⌘K on every action</small>
                </td>
                <td className="val yes">Included</td>
                <td className="val yes pro">Included</td>
              </tr>
              <tr>
                <td className="feat-name">
                  MCP server<small>Point your own agent at Needt</small>
                </td>
                <td className="val no">
                  <span className="soon">planned</span>
                </td>
                <td className="val pro">
                  <span className="soon">planned</span>
                </td>
              </tr>
              <tr className="cta-row">
                <td></td>
                <td>
                  <a className="btn btn-ghost" href="https://use.needt.app">
                    Start my free plan
                  </a>
                </td>
                <td className="pro">
                  <a className="btn btn-solid" href="https://use.needt.app">
                    Start my trial
                  </a>
                  <small
                    style={{
                      display: "block",
                      marginTop: "9px",
                      font: "400 12px/1.4 var(--f-mono)",
                      color: "rgba(0,0,0,.55)",
                    }}
                  >
                    14 days · no card
                  </small>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="lifetime reveal">
          <span className="lt-amt">
            $79<span className="was">$149</span>
          </span>
          <div className="lt-body">
            <strong>Lifetime — first 100 people</strong>
            <span>
              Everything in Pro, permanently, for one payment. Not a different product — the same one on a different
              payment schedule.
            </span>
          </div>
          <a className="btn btn-ghost" href="https://use.needt.app">
            Buy once
          </a>
        </div>
      </div>
    </section>
    </>
  )
}
