/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Steps() {
  return (
    <>
    {/* ============ STEPS ============ */}
    <section className="steps" id="how">
      <div className="wrap">
        <h2 className="reveal inflate" style={{ maxWidth: "20ch", marginBottom: "44px" }}>
          It works the way a good assistant would.
        </h2>
        <div className="steps-grid">
          <div id="steplist">
            <div className="step on" data-step="1">
              <p className="eyebrow">01</p>
              <h3>Everything arrives in one place</h3>
              <p>
                Google Calendar, Outlook and CalDAV sync into Needt and stay synced. Tasks come from your inbox,
                from ⌘K, or from a sentence typed anywhere. Nothing lives in a second app you have to remember to
                open.
              </p>
            </div>
            <div className="step" data-step="2">
              <p className="eyebrow">02</p>
              <h3>The work gets placed, not listed</h3>
              <p>
                Needt reads the week you actually have — meetings, working hours, the buffer you need between things
                — and puts each task in a slot where it fits. A list tells you what is undone. A schedule tells you
                when.
              </p>
            </div>
            <div className="step" data-step="3">
              <p className="eyebrow">03</p>
              <h3>You see the day before you keep it</h3>
              <p>
                Every reschedule is shown as a proposal: what moved, where it went, what stayed put. Keep it, or
                undo it and the day snaps back. Nothing is rearranged behind your back.
              </p>
            </div>
          </div>

          <div className="step-visual">
            <div className="panel on" data-panel="1">
              <div className="srcs">
                <div className="src">
                  <i>G</i>Google Calendar
                </div>
                <div className="src">
                  <i>O</i>Outlook
                </div>
                <div className="src">
                  <i>C</i>CalDAV
                </div>
                <div className="src">
                  <i>@</i>Task from email
                </div>
                <div className="src">
                  <i>⌘</i>Command palette
                </div>
                <div className="src">
                  <i>+</i>Quick add
                </div>
              </div>
            </div>
            <div className="panel" data-panel="2">
              <div className="slots">
                <div className="slot blocked">09:00 — Standup · fixed</div>
                <div className="slot taken">10:00 — Landing copy</div>
                <div className="slot">11:30 — open · 30 min</div>
                <div className="slot blocked">12:00 — Lunch · fixed</div>
                <div className="slot taken">14:00 — Ship pricing page</div>
                <div className="slot">15:30 — open · 60 min</div>
                <div className="slot blocked">16:30 — 1:1 with Kim · fixed</div>
              </div>
            </div>
            <div className="panel" data-panel="3">
              <div className="diff">
                <div className="row">
                  <span className="name">Ship pricing page</span>
                  <span className="from">14:00</span>
                  <span className="arw">→</span>
                  <span className="to">15:00</span>
                </div>
                <div className="row">
                  <span className="name">Invoices</span>
                  <span className="from">15:30</span>
                  <span className="arw">→</span>
                  <span className="to">11:30</span>
                </div>
                <div className="row">
                  <span className="name">1:1 with Kim</span>
                  <span className="to" style={{ color: "var(--slate)" }}>
                    16:30 · unchanged
                  </span>
                </div>
                <div className="diff-actions">
                  <button className="btn btn-solid" style={{ padding: "12px 20px", fontSize: "15px" }}>
                    Keep this day
                  </button>
                  <button className="btn btn-ghost" style={{ padding: "12px 20px", fontSize: "15px" }}>
                    Undo
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div className="spectrum"></div>
    </>
  )
}
