/* Generated by splitting the single-file port on 2026-08-26.
   Markup is unchanged from src/imports/index.html; only its container moved. */

export function Strip() {
  return (
    <>
    {/* ============ CONNECTIONS ============ */}
    <section className="strip">
      <div className="wrap">
        <div className="strip-inner reveal">
          <p className="eyebrow">Works with the calendar you already have</p>
          <span className="logo">
            <i>G</i>Google Calendar
          </span>
          <span className="logo">
            <i>O</i>Outlook
          </span>
          <span className="logo">
            <i>C</i>CalDAV
          </span>
          <span className="logo">
            <i>@</i>Your inbox
          </span>
          <span className="logo">
            <i>⌘</i>Command palette
          </span>
        </div>
      </div>
    </section>
    </>
  )
}
