/* Generated by splitting the single-file port on 2026-08-26. */

import { Agent } from "../sections/Agent"

export function AgentPage() {
  return (
    <main id="top" className="subpage">
      <div className="wrap subhead">
        <p className="eyebrow">The agent</p>
        <h1 className="display inflate in">It reads the day, then asks.</h1>
        <p className="lede">
          Every tool it holds is listed below, with the exact name it is called by.
          Nothing here is a category — these are the calls it can actually make.
        </p>
      </div>
      <Agent />
    </main>
  )
}
