/* Generated by splitting the single-file port on 2026-08-26. */

import { useHomeEffects } from "../effects"
import { Hero } from "../sections/Hero"
import { Strip } from "../sections/Strip"
import { Steps } from "../sections/Steps"
import { Inside } from "../sections/Inside"
import { Pricing } from "../sections/Pricing"
import { StickyCta } from "../components/StickyCta"

export function Home() {
  useHomeEffects()
  return (
    <>
      <main id="top">
        <Hero />
        <Strip />
        <Steps />
        <Inside />
        <Pricing />
      </main>
      <StickyCta />
    </>
  )
}
