/* Generated by splitting the single-file port on 2026-08-26. */

import { useHomeEffects } from "../effects"
import { Pricing } from "../sections/Pricing"
import { Faq } from "../sections/Faq"

export function PricingPage() {
  useHomeEffects()
  return (
    <main id="top" className="subpage">
      <div className="wrap subhead">
        <p className="eyebrow">Pricing</p>
        <h1 className="display inflate in">Two numbers, no seats.</h1>
        <p className="lede">
          Free while it is in beta. Every plan is per person — a shared workspace
          does not bill you for the people in it.
        </p>
      </div>
      <Pricing />
      <Faq />
    </main>
  )
}
