/* Generated by splitting the single-file port on 2026-08-26. */

import { useHomeEffects } from "../effects"
import { Faq } from "../sections/Faq"

export function SecurityPage() {
  useHomeEffects()
  return (
    <main id="top" className="subpage">
      <div className="wrap subhead">
        <p className="eyebrow">Security</p>
        <h1 className="display inflate in">What it can and cannot do.</h1>
        <p className="lede">
          Needt reads your calendar and, if you connect it, your mail. It has no
          ability to send anything on your behalf. Below is the same list of
          questions people ask before connecting an account.
        </p>
      </div>
      <Faq />
    </main>
  )
}
